

import "./globals.css";
import "./css/style.css"
import "./css/style.scss"
import "./css/animate.css"
import "./css/nice-select.css"
import "./css/swiper-bundle.min.css"
import "./css/bootstrap-icons.min.css"
import "./css/bootstrap.min.css"
import "./css/daterangepicker.css"
import "./css/dropzone.css"
import "./css/jquery.fancybox.min.css"
import  "bootstrap/dist/css/bootstrap.min.css"
import Footer from "./components/Footer";


export const metadata = {
  title: "Global Sky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <div>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}


