import localFont from "next/font/local";
import "./globals.css";
import "./css/style.css"
import "./css/style.scss"
import "./css/animate.css"
import "./css/nice-select.css"
import "./css/swiper-bundle.min.css"

import "./css/bootstrap-icons.min.css"
import "./css/bootstrap.min.css"

import "./css/daterangepicker.css"
import "./css/dropzone.css"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{textDecoration:"none"}} className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
